name: Maven Deploy Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to release. Must already exist.
        required: true

jobs:
  build:
    environment: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Verify the ref is actually a tag
        run: git tag --list | grep --line-regexp ${{ inputs.tag }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and deploy to Maven Central
        run: ./mvnw --batch-mode --settings deploy-settings.xml deploy -Dgpg.signer=bc -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
