name: Maven Deploy Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to release. Must already exist.
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Verify the ref is actually a tag
        run: git tag --list | grep --line-regexp ${{ inputs.tag }}

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

          server-id: 'central'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build and deploy to Maven Central
        run: ./mvnw deploy --batch-mode -Dgpg.signer=bc -Prelease
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.SDK_ROBOT_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ''

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::786014483886:role/SDK_GHA
          aws-region: us-west-1

      - name: Upload API documentation
        run: aws s3 cp --recursive --acl public-read couchbase-analytics-java-client/target/reports/apidocs/ s3://docs.couchbase.com/sdk-api/couchbase-analytics-java-client-${{ inputs.tag }}
